### ISSUE TITLE
Support for CentOS 6?

### ISSUE THREAD

**Issue by markwiater** [fac/auth-script-openvpn#9]
Compiling is failing for me on CentOS 6. older gcc? 

[mw@test auth-script-openvpn-master]# make
cc -O -Wall -Wextra -Wformat-security -fstack-protector-strong -D_FORTIFY_SOURCE=2 -std=c99 -D_POSIX_C_SOURCE=200809L -fPIC -shared -o auth_script.so auth_script.c
cc1: error: unrecognized command line option "-fstack-protector-strong"
make: *** [plugin] Error 1.

[mw@test auth-script-openvpn-master]# rpm -q openvpn gcc glibc
openvpn-2.4.4-1.el6.i686
gcc-4.4.7-18.el6.i686
glibc-2.12-1.209.el6_9.2.i686

Thanks, Mark

**Comment by caius** [comment]
@markwiater looks like CentOS 6's gcc (4.4 on my machine) doesn't support `-fstack-protector-strong` which is why it errors. If I comment that out in the `Makefile` I can get it to compile just fine.

I suspect we need to improve the Makefile to detect whether the current compiler supports that option or not to have it just work.

**Comment by markwiater** [comment]
@caius - Right, that's what I did, took those options out and it did compile. I wanted to leave this open in case it was a mistake to comment them.

thanks for the plugin, it was exactly what I needed to finish implementing a custom second authentication factor without the blocking.
